import { InputAdornment, TextField } from '@mui/material';
import { Close, Search } from '@mui/icons-material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useCallback, useEffect, useState } from 'react';
import { searchCocktails } from '../api/cocktail';
import { Cocktail } from '../models';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  const router = useRouter();
  const [searchTerm, setSearchTerm] = useState('');
  const [results, setResults] = useState<Cocktail[]>([]);

  const clearSearch = () => setSearchTerm('');

  const fetchResults = useCallback(async () => {
    const drinks = await searchCocktails(searchTerm);
    setResults(drinks);
  }, [searchTerm]);

  const routeToResult = (result: Cocktail) => {
    router.push(`/cocktails/${result.idDrink}`);
  };

  useEffect(() => {
    let searchTimeout: NodeJS.Timeout;

    if (searchTerm.length > 0) {
      searchTimeout = setTimeout(() => fetchResults(), 200);
    } else {
      setResults([]);
    }

    return () => clearTimeout(searchTimeout);
  }, [searchTerm, fetchResults]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Thirsty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Thirsty</h1>

        <TextField
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <Search />
              </InputAdornment>
            ),
            endAdornment: (
              <InputAdornment position="end" onClick={clearSearch}>
                <Close />
              </InputAdornment>
            ),
          }}
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
        ></TextField>

        <div className={styles.grid}>
          <ul>
            {results.map(result => (
              <li key={result.idDrink} onClick={() => routeToResult(result)}>
                <h4>{result.strDrink}</h4>
              </li>
            ))}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
