import { CircularProgress, InputAdornment, TextField } from '@mui/material';
import { Close, Search } from '@mui/icons-material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useCallback, useEffect, useState } from 'react';
import { searchCocktails } from '../api/cocktail';
import { Cocktail } from '../models';

const Home: NextPage = () => {
  const router = useRouter();
  const [searchTerm, setSearchTerm] = useState('');
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<Cocktail[]>([]);

  const clearSearch = () => setSearchTerm('');

  const fetchResults = useCallback(async () => {
    const drinks = await searchCocktails(searchTerm);
    setResults(drinks);
    setLoading(false);
  }, [searchTerm]);

  const routeToResult = (result: Cocktail) => {
    router.push(`/cocktails/${result.idDrink}`);
  };

  const EndAdornment = () =>
    searchTerm.length > 0 ? (
      <InputAdornment position="end" onClick={clearSearch}>
        {loading ? <CircularProgress /> : <Close />}
      </InputAdornment>
    ) : (
      <></>
    );

  useEffect(() => {
    let searchTimeout: NodeJS.Timeout;

    if (searchTerm.length > 0) {
      setLoading(true);
      searchTimeout = setTimeout(() => fetchResults(), 200);
    } else {
      setResults([]);
    }

    return () => clearTimeout(searchTimeout);
  }, [searchTerm, fetchResults]);

  return (
    <div className="container">
      <Head>
        <title>Thirsty</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="main">
        <h1 className="title">Thirsty</h1>

        <TextField
          value={searchTerm}
          onChange={e => setSearchTerm(e.target.value)}
          placeholder="Find a drink"
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <Search />
              </InputAdornment>
            ),
            endAdornment: <EndAdornment />,
          }}
        ></TextField>

        <div className="grid">
          <ul>
            {results.map(result => (
              <li key={result.idDrink} onClick={() => routeToResult(result)}>
                <h4>{result.strDrink}</h4>
              </li>
            ))}
          </ul>
        </div>
      </main>

      <footer className="footer"></footer>
    </div>
  );
};

export default Home;
